name: Run Flask API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flask pytest requests

      - name: Start Flask server
        run: |
          python app.py &
          sleep 5  # Espera para asegurarse de que el servidor está activo

      - name: Run tests
        run: pytest tests.py -v
